/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_voxelwind_server_jni_hash_NativeHashImpl */

#ifndef _Included_com_voxelwind_server_jni_hash_NativeHashImpl
#define _Included_com_voxelwind_server_jni_hash_NativeHashImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_voxelwind_server_jni_hash_NativeHashImpl
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_voxelwind_server_jni_hash_NativeHashImpl_init
  (JNIEnv *, jobject);

/*
 * Class:     com_voxelwind_server_jni_hash_NativeHashImpl
 * Method:    update
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_voxelwind_server_jni_hash_NativeHashImpl_update
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_voxelwind_server_jni_hash_NativeHashImpl
 * Method:    digest
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_voxelwind_server_jni_hash_NativeHashImpl_digest
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_voxelwind_server_jni_hash_NativeHashImpl
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_voxelwind_server_jni_hash_NativeHashImpl_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
